### ISSUE TITLE
[Bug] Error: Cannot find module 'lodash/clonedeep'

### ISSUE THREAD

**Issue by Quayle57** [smashtestio/smashtest#3]
Hello, 
I'm on Debian buster and I tried to install smashtest:
`npm i -g smashtest`
```bash
$ npm i -g --no-cache smashtest
/home/user/npm/bin/smashtest -> /home/user/npm/lib/node_modules/smashtest/src/cli.js

> sharp@0.22.1 install /home/user/npm/lib/node_modules/smashtest/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.11.2 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/user/npm/lib/node_modules/smashtest/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory '/home/user/npm/lib/node_modules/smashtest/node_modules/sharp/build'
+ smashtest@1.0.17-beta
added 187 packages in 44.815s

$ smashtest 
internal/modules/cjs/loader.js:550
    throw err;
    ^
Error: Cannot find module 'lodash/clonedeep'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/user/npm/lib/node_modules/smashtest/src/step.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

```

But I can't run it because of a `lodash` error

I tried without the  `-g` too in one of my project

**Comment by Quayle57** [comment]
Okay I found the problem:
In `src/step.js` and `src/branch.js` you `require('lodash/clonedeep');` but you should `require('lodash/cloneDeep');`

**Comment by vptes1** [comment]
Must be a Debian thing. I'll push a fix.

**Comment by vptes1** [comment]
Fixed in https://github.com/smashtestio/smashtest/commit/4284437b76fd1ed1c3459360950af0e5a6e232eb
