### ISSUE TITLE
CI - DevToolsPort doesn't exist

### ISSUE THREAD

**Issue by clementbmn** [smashtestio/smashtest#62]
Hi, 

I'm trying to integrate our smashtest tests suite into our Gitlab CI
I'm running a docker container in which I install google-chrome and chromedriver, but at the moment to Open Chrome, I got a crash complaining that DevToolsActivePort file doesn't exist
From my few researches, it seems that passing some args (--headless, --no-sandbox, --disable-dev-shm-usage) should work but did not find a way to pass these arguments to chrome by smashtest

Here are my logs

```    Open Chrome                                      setup.smash:3 --> browser.smash:19

Open Chrome
WebDriverError: unknown error: Chrome failed to start: exited abnormally   [/app/src/tests/integrations/root/setup.smash:3]
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-55-generic x86_64)
    at Object.checkLegacyResponse (/app/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:554:13)
    at Executor.execute (/app/node_modules/selenium-webdriver/lib/http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

00:00:04 | 17 failed | 17 skipped | 34 branches complete```

**Comment by vptes1** [comment]
Try setting options for the browser before it's opened.
See https://smashtest.io/ui-testing/capabilities
